# Generated by Django 5.2.16 on 2026-08-01 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("imaging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("algorithm_name", models.CharField(max_length=255)),
                ("algorithm_version", models.CharField(max_length=64)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_runs",
                        to="imaging.imagingstudy",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "name"),
            },
        ),
        migrations.CreateModel(
            name="MeasurementResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.DecimalField(decimal_places=8, max_digits=20)),
                ("unit", models.CharField(max_length=64)),
                ("region_label", models.CharField(blank=True, max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="analysis.analysisrun",
                    ),
                ),
            ],
            options={
                "ordering": ("analysis_run_id", "name", "region_label"),
            },
        ),
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(
                fields=["study", "status"], name="analysis_run_study_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(
                fields=["algorithm_name"], name="analysis_run_algorithm_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(fields=["created_at"], name="analysis_run_created_idx"),
        ),
        migrations.AddIndex(
            model_name="measurementresult",
            index=models.Index(
                fields=["analysis_run", "name"], name="measurement_run_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="measurementresult",
            index=models.Index(fields=["region_label"], name="measurement_region_idx"),
        ),
        migrations.AddIndex(
            model_name="measurementresult",
            index=models.Index(fields=["created_at"], name="measurement_created_idx"),
        ),
    ]
