# Generated by Django 5.2.16 on 2026-08-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
        ("imaging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualizationArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("rescale", "Rescale"),
                            ("gaussian", "Gaussian"),
                            ("sobel", "Sobel"),
                        ],
                        max_length=16,
                    ),
                ),
                ("modality", models.CharField(max_length=16)),
                ("slice_index", models.PositiveIntegerField()),
                ("value_units", models.CharField(max_length=64)),
                ("relative_path", models.CharField(max_length=512, unique=True)),
                ("mime_type", models.CharField(default="image/png", max_length=64)),
                ("file_size_bytes", models.PositiveBigIntegerField()),
                ("file_sha256", models.CharField(db_index=True, max_length=64)),
                ("rows", models.PositiveIntegerField()),
                ("columns", models.PositiveIntegerField()),
                ("colormap", models.CharField(max_length=64)),
                ("display_minimum", models.FloatField()),
                ("display_maximum", models.FloatField()),
                ("window_center", models.FloatField(blank=True, null=True)),
                ("window_width", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualization_artifacts",
                        to="imaging.imaginginstance",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "relative_path"),
            },
        ),
        migrations.AddIndex(
            model_name="visualizationartifact",
            index=models.Index(fields=["operation"], name="vis_artifact_operation_idx"),
        ),
        migrations.AddIndex(
            model_name="visualizationartifact",
            index=models.Index(fields=["modality"], name="vis_artifact_modality_idx"),
        ),
        migrations.AddIndex(
            model_name="visualizationartifact",
            index=models.Index(fields=["created_at"], name="vis_artifact_created_idx"),
        ),
    ]
