# Generated by Django 5.2.16 on 2026-08-01 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImagingStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("study_instance_uid", models.CharField(max_length=64, unique=True)),
                ("accession_number", models.CharField(blank=True, max_length=64)),
                ("study_description", models.CharField(blank=True, max_length=255)),
                ("modality_summary", models.CharField(blank=True, max_length=128)),
                ("study_date", models.DateField(blank=True, null=True)),
                ("source_dataset", models.CharField(blank=True, max_length=128)),
                ("source_subject_id", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-study_date", "study_instance_uid"),
                "indexes": [
                    models.Index(fields=["study_date"], name="imaging_study_date_idx"),
                    models.Index(
                        fields=["source_dataset"], name="imaging_study_source_idx"
                    ),
                    models.Index(
                        fields=["accession_number"], name="imaging_study_accession_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ImagingSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series_instance_uid", models.CharField(max_length=64, unique=True)),
                ("modality", models.CharField(max_length=16)),
                ("series_description", models.CharField(blank=True, max_length=255)),
                ("body_part_examined", models.CharField(blank=True, max_length=64)),
                ("image_orientation_patient", models.JSONField(blank=True, null=True)),
                ("image_position_patient", models.JSONField(blank=True, null=True)),
                ("pixel_spacing", models.JSONField(blank=True, null=True)),
                (
                    "slice_thickness",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("number_of_instances", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="imaging.imagingstudy",
                    ),
                ),
            ],
            options={
                "ordering": ("study_id", "modality", "series_instance_uid"),
            },
        ),
        migrations.CreateModel(
            name="ImagingInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sop_instance_uid", models.CharField(max_length=64, unique=True)),
                ("sop_class_uid", models.CharField(blank=True, max_length=64)),
                ("instance_number", models.IntegerField(blank=True, null=True)),
                ("rows", models.PositiveIntegerField(blank=True, null=True)),
                ("columns", models.PositiveIntegerField(blank=True, null=True)),
                ("file_sha256", models.CharField(blank=True, max_length=64)),
                ("orthanc_instance_id", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="imaging.imagingseries",
                    ),
                ),
            ],
            options={
                "ordering": ("series_id", "instance_number", "sop_instance_uid"),
                "indexes": [
                    models.Index(
                        fields=["series", "instance_number"],
                        name="img_instance_series_num_idx",
                    ),
                    models.Index(
                        fields=["file_sha256"], name="imaging_instance_sha_idx"
                    ),
                    models.Index(
                        fields=["orthanc_instance_id"],
                        name="imaging_instance_orthanc_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="imagingseries",
            index=models.Index(
                fields=["study", "modality"], name="imaging_series_study_mod_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagingseries",
            index=models.Index(fields=["modality"], name="imaging_series_modality_idx"),
        ),
        migrations.AddIndex(
            model_name="imagingseries",
            index=models.Index(
                fields=["body_part_examined"], name="imaging_series_body_part_idx"
            ),
        ),
    ]
