# Generated by Django 5.2.16 on 2026-08-02 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imaging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalDicomFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relative_path", models.CharField(max_length=512)),
                ("file_sha256", models.CharField(db_index=True, max_length=64)),
                ("file_size_bytes", models.PositiveBigIntegerField()),
                ("is_available", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_file",
                        to="imaging.imaginginstance",
                    ),
                ),
            ],
            options={
                "ordering": ("relative_path",),
            },
        ),
    ]
