# Generated by Django 5.2.16 on 2026-08-01 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("local_manifest", "Local manifest"),
                            ("orthanc", "Orthanc"),
                            ("tcia_manifest", "TCIA manifest"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_name", models.CharField(max_length=255)),
                ("source_uri", models.CharField(blank=True, max_length=512)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at", "source_name"),
                "indexes": [
                    models.Index(fields=["status"], name="ingestion_job_status_idx"),
                    models.Index(
                        fields=["source_type"], name="ingestion_job_source_type_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="ingestion_job_created_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IngestionJobEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="ingestion.ingestionjob",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["job", "created_at"],
                        name="ingest_event_job_created_idx",
                    ),
                    models.Index(fields=["level"], name="ingestion_event_level_idx"),
                ],
            },
        ),
    ]
